-- Phase 3 first manual backfill measurement.
-- Predeclared target: p95 fetch-to-curated <= 86,400 seconds (24 hours).
-- Sample: loaded origin attempts requested within the five-year horizon
-- 2021-09-29 through 2026-09-29 UTC; includes one overlapping Seattle sample.

SELECT COUNT(*) AS SAMPLE_ATTEMPTS,
       MIN(REQUESTED_STARTTIME) AS EARLIEST_REQUESTED_START,
       MAX(REQUESTED_ENDTIME) AS LATEST_REQUESTED_END,
       MIN(FETCHED_AT) AS FIRST_FETCH,
       MAX(CURATED_AT) AS LAST_CURATED,
       MIN(FETCH_TO_CURATED_SECONDS) AS MIN_SECONDS,
       ROUND(PERCENTILE_CONT(0.5) WITHIN GROUP
             (ORDER BY FETCH_TO_CURATED_SECONDS), 1) AS P50_SECONDS,
       ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP
             (ORDER BY FETCH_TO_CURATED_SECONDS), 1) AS P95_SECONDS,
       MAX(FETCH_TO_CURATED_SECONDS) AS MAX_SECONDS
FROM QUAKEWATCH.CURATED.FACT_BATCH_RUN
WHERE BATCH_KIND = 'origin'
  AND PROCESS_STATUS = 'complete'
  AND FETCH_TO_CURATED_SECONDS IS NOT NULL
  AND REQUESTED_STARTTIME >= TO_TIMESTAMP_TZ('2021-09-29T00:00:00Z')
  AND REQUESTED_ENDTIME <= TO_TIMESTAMP_TZ('2026-09-29T00:00:00Z');

SELECT MAX(a.FETCHED_AT) AS LAST_SUCCESSFUL_FETCH,
       DATEDIFF('second', MAX(a.FETCHED_AT), CURRENT_TIMESTAMP())
           AS LAST_SUCCESSFUL_FETCH_AGE_SECONDS,
       MAX(s.SOURCE_UPDATED_AT) AS NEWEST_ACCEPTED_SOURCE_UPDATE,
       DATEDIFF('second', MAX(s.SOURCE_UPDATED_AT), CURRENT_TIMESTAMP())
           AS NEWEST_ACCEPTED_SOURCE_AGE_SECONDS
FROM QUAKEWATCH.CURATED.V_BATCH_HEALTH a
LEFT JOIN QUAKEWATCH.CURATED.STG_EVENT_REVISION s
  ON a.ATTEMPT_ID = s.ATTEMPT_ID AND s.REJECT_REASON IS NULL
WHERE a.HEALTH_STATUS = 'RECONCILED';
