-- Phase 3 read-only reconciliation queries. Apply health views first.
-- Pending processing is reported separately from a failed count check.

SELECT HEALTH_STATUS, COUNT(*) AS ATTEMPTS,
       SUM(LOADED_ROWS) AS RECEIPT_LOADED_ROWS,
       SUM(RAW_ROWS) AS OBSERVED_RAW_ROWS,
       SUM(STAGING_ROWS) AS OBSERVED_STAGING_ROWS,
       SUM(COALESCE(PROCESSED_ROWS, 0)) AS PROCESSED_ROWS,
       SUM(COALESCE(REJECTED_ROWS, 0)) AS REJECTED_ROWS
FROM QUAKEWATCH.CURATED.V_BATCH_HEALTH
GROUP BY HEALTH_STATUS
ORDER BY HEALTH_STATUS;

SELECT ATTEMPT_ID, HEALTH_STATUS, LOADED_ROWS, RAW_ROWS,
       STAGING_ROWS, PROCESSED_ROWS, REJECTED_ROWS, RECEIPT_GAP_COUNT
FROM QUAKEWATCH.CURATED.V_BATCH_HEALTH
WHERE HEALTH_STATUS NOT IN ('RECONCILED', 'PENDING_PROCESS')
ORDER BY ATTEMPT_ID;

SELECT ATTEMPT_ID, WINDOW_ID, WINDOW_STATUS,
       COUNT_BEFORE, RETURNED_ROWS, COUNT_AFTER
FROM QUAKEWATCH.CURATED.V_RECEIPT_WINDOW_AUDIT
WHERE WINDOW_STATUS = 'unresolved'
   OR (COUNT_BEFORE IS NOT NULL AND RETURNED_ROWS IS NOT NULL
       AND COUNT_AFTER IS NOT NULL
       AND (COUNT_BEFORE <> RETURNED_ROWS OR RETURNED_ROWS <> COUNT_AFTER))
ORDER BY ATTEMPT_ID, WINDOW_ID;
