-- Phase 2 fixture database setup: REVIEW ONLY. Do not run without approval
-- approval for account changes and possible Snowflake charges.
-- CREATE DATABASE has no IF NOT EXISTS guard: stop if the name is occupied.
-- The project role receives only privileges needed to own fixture objects.

USE ROLE ACCOUNTADMIN;

CREATE DATABASE QUAKEWATCH_PHASE2_FIXTURE;
CREATE SCHEMA QUAKEWATCH_PHASE2_FIXTURE.RAW;
CREATE SCHEMA QUAKEWATCH_PHASE2_FIXTURE.CURATED;

GRANT USAGE ON DATABASE QUAKEWATCH_PHASE2_FIXTURE TO ROLE QUAKEWATCH_ROLE;
GRANT USAGE ON SCHEMA QUAKEWATCH_PHASE2_FIXTURE.RAW TO ROLE QUAKEWATCH_ROLE;
GRANT USAGE ON SCHEMA QUAKEWATCH_PHASE2_FIXTURE.CURATED TO ROLE QUAKEWATCH_ROLE;

GRANT CREATE TABLE ON SCHEMA QUAKEWATCH_PHASE2_FIXTURE.RAW TO ROLE QUAKEWATCH_ROLE;
GRANT CREATE STAGE ON SCHEMA QUAKEWATCH_PHASE2_FIXTURE.RAW TO ROLE QUAKEWATCH_ROLE;
GRANT CREATE TABLE ON SCHEMA QUAKEWATCH_PHASE2_FIXTURE.CURATED TO ROLE QUAKEWATCH_ROLE;
GRANT CREATE VIEW ON SCHEMA QUAKEWATCH_PHASE2_FIXTURE.CURATED TO ROLE QUAKEWATCH_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA QUAKEWATCH_PHASE2_FIXTURE.CURATED TO ROLE QUAKEWATCH_ROLE;

-- The later, separately approved deployment uses QUAKEWATCH_ROLE to create
-- fixture tables, stage, view, and procedure in this database only.
