-- Phase 3 bounded sample analysis, public Seattle point, 2026-09-28 UTC.
-- This queries only currently modeled events; it does not imply full coverage.

SELECT b.SITE_KEY,
       COUNT(*) AS CURRENT_EVENTS_WITHIN_RADIUS,
       MIN(e.MAGNITUDE) AS MIN_MAGNITUDE,
       MAX(e.MAGNITUDE) AS MAX_MAGNITUDE,
       MIN(e.ORIGIN_TIME) AS EARLIEST_ORIGIN,
       MAX(e.ORIGIN_TIME) AS LATEST_ORIGIN
FROM QUAKEWATCH.CURATED.EVENT_CURRENT e
JOIN QUAKEWATCH.CURATED.BRIDGE_EVENT_SITE b
  ON e.CANONICAL_EVENT_ID = b.CANONICAL_EVENT_ID
 AND e.SOURCE_UPDATED_AT = b.SOURCE_UPDATED_AT
 AND e.PAYLOAD_HASH = b.PAYLOAD_HASH
WHERE b.SITE_KEY = 'seattle'
  AND b.WITHIN_RADIUS = TRUE
  AND e.ORIGIN_TIME >= TO_TIMESTAMP_TZ('2026-09-28T00:00:00Z')
  AND e.ORIGIN_TIME < TO_TIMESTAMP_TZ('2026-09-29T00:00:00Z')
GROUP BY b.SITE_KEY;
