-- REVIEW ONLY. Running this SELECT may resume QUAKEWATCH_WH and incur credits.
-- Ten public-site, bounded event-time aggregates for optional Cortex evaluation.
-- A modeled count is not proof of complete USGS source coverage.
WITH CASES (CASE_ID, SITE_KEY, START_UTC, END_UTC) AS (
    SELECT COLUMN1, COLUMN2, COLUMN3, COLUMN4 FROM VALUES
      ('seattle-2022', 'seattle', '2022-01-01T00:00:00Z', '2023-01-01T00:00:00Z'),
      ('sf-2022', 'san-francisco', '2022-01-01T00:00:00Z', '2023-01-01T00:00:00Z'),
      ('anchorage-2022', 'anchorage', '2022-01-01T00:00:00Z', '2023-01-01T00:00:00Z'),
      ('seattle-2024', 'seattle', '2024-01-01T00:00:00Z', '2025-01-01T00:00:00Z'),
      ('sf-2024', 'san-francisco', '2024-01-01T00:00:00Z', '2025-01-01T00:00:00Z'),
      ('anchorage-2024', 'anchorage', '2024-01-01T00:00:00Z', '2025-01-01T00:00:00Z'),
      ('seattle-2026', 'seattle', '2026-01-01T00:00:00Z', '2026-09-29T00:00:00Z'),
      ('sf-2026', 'san-francisco', '2026-01-01T00:00:00Z', '2026-09-29T00:00:00Z'),
      ('anchorage-2026', 'anchorage', '2026-01-01T00:00:00Z', '2026-09-29T00:00:00Z'),
      ('seattle-day', 'seattle', '2026-09-28T00:00:00Z', '2026-09-29T00:00:00Z')
), SITE_RADII AS (
    SELECT SITE_KEY, MAX(RADIUS_KM) AS RADIUS_KM,
           COUNT(DISTINCT RADIUS_KM) AS DISTINCT_RADII
    FROM QUAKEWATCH.CURATED.DIM_SITE
    WHERE SITE_KEY IN ('seattle', 'san-francisco', 'anchorage')
    GROUP BY SITE_KEY
), MATCHED AS (
    SELECT c.CASE_ID, e.CANONICAL_EVENT_ID, e.SOURCE_UPDATED_AT,
           e.PAYLOAD_HASH, e.MAGNITUDE, e.SOURCE_STATUS,
           b.EPICENTRAL_DISTANCE_KM,
           ROW_NUMBER() OVER (
               PARTITION BY c.CASE_ID, e.CANONICAL_EVENT_ID
               ORDER BY e.SOURCE_UPDATED_AT DESC, e.PAYLOAD_HASH DESC,
                        b.EPICENTRAL_DISTANCE_KM
           ) AS DEDUP_RANK
    FROM CASES c
    JOIN QUAKEWATCH.CURATED.BRIDGE_EVENT_SITE b
      ON b.SITE_KEY = c.SITE_KEY AND b.WITHIN_RADIUS = TRUE
    JOIN QUAKEWATCH.CURATED.EVENT_CURRENT e
      ON e.CANONICAL_EVENT_ID = b.CANONICAL_EVENT_ID
     AND e.SOURCE_UPDATED_AT = b.SOURCE_UPDATED_AT
     AND e.PAYLOAD_HASH = b.PAYLOAD_HASH
    WHERE e.ORIGIN_TIME >= TO_TIMESTAMP_TZ(c.START_UTC)
      AND e.ORIGIN_TIME < TO_TIMESTAMP_TZ(c.END_UTC)
), RANKED AS (
    SELECT *, ROW_NUMBER() OVER (
        PARTITION BY CASE_ID
        ORDER BY EPICENTRAL_DISTANCE_KM, CANONICAL_EVENT_ID
    ) AS NEAREST_RANK
    FROM MATCHED
    WHERE DEDUP_RANK = 1
), AGGREGATED AS (
    SELECT CASE_ID, COUNT(*) AS EVENT_COUNT,
           MAX(IFF(NEAREST_RANK = 1, CANONICAL_EVENT_ID, NULL)) AS NEAREST_EVENT_ID,
           MAX(IFF(NEAREST_RANK = 1, ROUND(EPICENTRAL_DISTANCE_KM, 1), NULL)) AS NEAREST_DISTANCE_KM,
           MAX(IFF(NEAREST_RANK = 1, MAGNITUDE, NULL)) AS NEAREST_MAGNITUDE,
           MAX(IFF(NEAREST_RANK = 1, SOURCE_STATUS, NULL)) AS NEAREST_SOURCE_STATUS,
           MAX(IFF(NEAREST_RANK = 1,
               ROUND(DATEDIFF('minute', SOURCE_UPDATED_AT, CURRENT_TIMESTAMP()) / 60.0, 1),
               NULL)) AS NEAREST_RECORD_AGE_HOURS
    FROM RANKED
    GROUP BY CASE_ID
)
SELECT c.CASE_ID, c.SITE_KEY, c.START_UTC, c.END_UTC,
       s.RADIUS_KM, s.DISTINCT_RADII,
       COALESCE(a.EVENT_COUNT, 0) AS EVENT_COUNT,
       a.NEAREST_EVENT_ID, a.NEAREST_DISTANCE_KM, a.NEAREST_MAGNITUDE,
       a.NEAREST_SOURCE_STATUS, a.NEAREST_RECORD_AGE_HOURS,
       CURRENT_TIMESTAMP() AS CHECKED_AT
FROM CASES c
LEFT JOIN SITE_RADII s ON s.SITE_KEY = c.SITE_KEY
LEFT JOIN AGGREGATED a ON a.CASE_ID = c.CASE_ID
ORDER BY c.CASE_ID;
