-- Phase 3 read-only reporting views. Apply only after Snowflake cost approval.
-- These views observe attempts with a durable Snowflake RAW receipt. Local
-- failed extracts that were never loaded remain in local manifests/results.

CREATE VIEW QUAKEWATCH.CURATED.V_BATCH_HEALTH AS
WITH RAW_COUNTS AS (
    SELECT ATTEMPT_ID, COUNT(*) AS RAW_ROWS
    FROM QUAKEWATCH.RAW.RAW_EVENT_RECORDS
    GROUP BY ATTEMPT_ID
), STAGING_COUNTS AS (
    SELECT ATTEMPT_ID, COUNT(*) AS STAGING_ROWS,
           COUNT_IF(REJECT_REASON IS NOT NULL) AS REJECT_ROWS
    FROM QUAKEWATCH.CURATED.STG_EVENT_REVISION
    GROUP BY ATTEMPT_ID
), LATEST_PROCESS AS (
    SELECT ATTEMPT_ID, PROCESS_ATTEMPT_ID, STATUS, FINISHED_AT,
           LOADED_ROWS, PROCESSED_ROWS, REJECTED_ROWS,
           ROW_NUMBER() OVER (
               PARTITION BY ATTEMPT_ID
               ORDER BY FINISHED_AT DESC, PROCESS_ATTEMPT_ID DESC
           ) AS PROCESS_RANK
    FROM QUAKEWATCH.CURATED.BATCH_PROCESS_ATTEMPT
)
SELECT a.ATTEMPT_ID, a.LOGICAL_BATCH_ID, a.BATCH_KIND, a.SITE_KEY,
       a.REQUESTED_STARTTIME, a.REQUESTED_ENDTIME, a.FETCHED_AT,
       a.EXTRACT_STATUS, a.LOAD_STATUS,
       a.SOURCE_ROWS_RETURNED, a.RAW_ROWS_WRITTEN, a.LOADED_ROWS,
       COALESCE(r.RAW_ROWS, 0) AS RAW_ROWS,
       COALESCE(s.STAGING_ROWS, 0) AS STAGING_ROWS,
       COALESCE(s.REJECT_ROWS, 0) AS STAGING_REJECT_ROWS,
       p.PROCESS_ATTEMPT_ID, p.STATUS AS PROCESS_STATUS,
       p.PROCESSED_ROWS, p.REJECTED_ROWS,
       f.PROCESS_STATUS AS FACT_PROCESS_STATUS,
       f.FETCH_TO_CURATED_SECONDS,
       COALESCE(ARRAY_SIZE(a.COVERAGE_GAPS), 0) AS RECEIPT_GAP_COUNT,
       CASE
           WHEN COALESCE(ARRAY_SIZE(a.COVERAGE_GAPS), 0) > 0 THEN 'SOURCE_GAP'
           WHEN a.LOAD_STATUS <> 'complete' THEN 'LOAD_INCOMPLETE'
           WHEN a.SOURCE_ROWS_RETURNED IS NULL OR a.RAW_ROWS_WRITTEN IS NULL
             OR a.LOADED_ROWS IS NULL
             OR a.SOURCE_ROWS_RETURNED <> a.RAW_ROWS_WRITTEN
             OR a.RAW_ROWS_WRITTEN <> a.LOADED_ROWS
             OR a.LOADED_ROWS <> COALESCE(r.RAW_ROWS, 0)
             THEN 'RAW_COUNT_MISMATCH'
           WHEN p.PROCESS_ATTEMPT_ID IS NULL THEN 'PENDING_PROCESS'
           WHEN p.STATUS <> 'complete' THEN 'PROCESS_FAILED'
           WHEN p.LOADED_ROWS IS NULL OR p.PROCESSED_ROWS IS NULL
             OR p.REJECTED_ROWS IS NULL OR f.PROCESSED_ROWS IS NULL
             OR f.REJECTED_ROWS IS NULL
             OR p.LOADED_ROWS <> a.LOADED_ROWS
             OR p.PROCESSED_ROWS <> p.LOADED_ROWS
             OR p.REJECTED_ROWS > p.PROCESSED_ROWS
             OR COALESCE(s.STAGING_ROWS, 0) <> p.LOADED_ROWS
             OR COALESCE(s.REJECT_ROWS, 0) <> p.REJECTED_ROWS
             OR f.ATTEMPT_ID IS NULL
             OR f.PROCESS_STATUS <> 'complete'
             OR f.PROCESSED_ROWS <> p.PROCESSED_ROWS
             OR f.REJECTED_ROWS <> p.REJECTED_ROWS
             THEN 'PROCESS_COUNT_MISMATCH'
           ELSE 'RECONCILED'
       END AS HEALTH_STATUS
FROM QUAKEWATCH.RAW.BATCH_ATTEMPT a
LEFT JOIN RAW_COUNTS r ON a.ATTEMPT_ID = r.ATTEMPT_ID
LEFT JOIN STAGING_COUNTS s ON a.ATTEMPT_ID = s.ATTEMPT_ID
LEFT JOIN LATEST_PROCESS p ON a.ATTEMPT_ID = p.ATTEMPT_ID
                          AND p.PROCESS_RANK = 1
LEFT JOIN QUAKEWATCH.CURATED.FACT_BATCH_RUN f ON a.ATTEMPT_ID = f.ATTEMPT_ID;

CREATE VIEW QUAKEWATCH.CURATED.V_RECEIPT_WINDOW_AUDIT AS
SELECT a.ATTEMPT_ID, a.BATCH_KIND,
       w.value:window_id::VARCHAR AS WINDOW_ID,
       w.value:status::VARCHAR AS WINDOW_STATUS,
       TRY_TO_TIMESTAMP_TZ(w.value:starttime::VARCHAR) AS WINDOW_STARTTIME,
       TRY_TO_TIMESTAMP_TZ(w.value:endtime::VARCHAR) AS WINDOW_ENDTIME,
       w.value:count_before::NUMBER(38, 0) AS COUNT_BEFORE,
       w.value:returned_rows::NUMBER(38, 0) AS RETURNED_ROWS,
       w.value:count_after::NUMBER(38, 0) AS COUNT_AFTER,
       COALESCE(ARRAY_SIZE(a.COVERAGE_GAPS), 0) AS RECEIPT_GAP_COUNT
FROM QUAKEWATCH.RAW.BATCH_ATTEMPT a,
     LATERAL FLATTEN(INPUT => a.WINDOW_AUDIT) w;

CREATE VIEW QUAKEWATCH.CURATED.V_EVENT_REJECTS AS
SELECT ATTEMPT_ID, WINDOW_ID, STAGE_FILE_NAME, STAGE_FILE_ROW_NUMBER,
       SOURCE_EVENT_ID, REJECT_REASON, PROJECTED_AT
FROM QUAKEWATCH.CURATED.STG_EVENT_REVISION
WHERE REJECT_REASON IS NOT NULL;
