-- Phase 2 batch-run fact. Local DDL only; apply after cost approval.
-- Grain: one extract/load ATTEMPT_ID, including failed attempts.
-- The Snowpark procedure owns MERGE updates; RAW.BATCH_ATTEMPT remains append-only.
CREATE TABLE IF NOT EXISTS QUAKEWATCH.CURATED.FACT_BATCH_RUN (
    ATTEMPT_ID VARCHAR NOT NULL,
    LOGICAL_BATCH_ID VARCHAR NOT NULL,
    BATCH_KIND VARCHAR NOT NULL,
    SITE_KEY VARCHAR,
    REQUESTED_STARTTIME TIMESTAMP_TZ NOT NULL,
    REQUESTED_ENDTIME TIMESTAMP_TZ NOT NULL,
    FETCHED_AT TIMESTAMP_TZ,
    RAW_RECORDED_AT TIMESTAMP_TZ,
    CURATED_AT TIMESTAMP_TZ,
    SOURCE_ROWS_RETURNED NUMBER(38, 0) NOT NULL,
    RAW_ROWS_WRITTEN NUMBER(38, 0) NOT NULL,
    LOADED_ROWS NUMBER(38, 0) NOT NULL,
    PROCESSED_ROWS NUMBER(38, 0),
    REJECTED_ROWS NUMBER(38, 0),
    FETCH_TO_CURATED_SECONDS NUMBER(38, 3),
    EXTRACT_STATUS VARCHAR NOT NULL,
    LOAD_STATUS VARCHAR NOT NULL,
    PROCESS_STATUS VARCHAR NOT NULL,
    LAST_PROCESS_ATTEMPT_ID VARCHAR,
    COVERAGE_GAPS VARIANT,
    RECONCILIATION_OK BOOLEAN,
    UPDATED_AT TIMESTAMP_TZ NOT NULL
)
COMMENT = 'One extract/load attempt with source, load, processing, reject and gap measures';
