-- Phase 2 typed staging. Apply with QUAKEWATCH_ROLE only after cost approval.
-- Grain: one RAW source observation, identified by its staged file and row.
-- The Snowpark procedure owns inserts and updates to this table.
CREATE TABLE IF NOT EXISTS QUAKEWATCH.CURATED.STG_EVENT_REVISION (
    STAGE_FILE_NAME VARCHAR NOT NULL,
    STAGE_FILE_ROW_NUMBER NUMBER(38, 0) NOT NULL,
    ATTEMPT_ID VARCHAR NOT NULL,
    WINDOW_ID VARCHAR NOT NULL,
    FETCHED_AT TIMESTAMP_TZ NOT NULL,
    PAYLOAD_HASH VARCHAR(64) NOT NULL,
    RAW_PARSER_VERSION VARCHAR NOT NULL,
    STAGING_PARSER_VERSION VARCHAR NOT NULL,
    SOURCE_EVENT_ID VARCHAR,
    ORIGIN_TIME TIMESTAMP_TZ,
    SOURCE_UPDATED_AT TIMESTAMP_TZ,
    SOURCE_STATUS VARCHAR,
    ASSOCIATED_IDS VARIANT,
    MAGNITUDE FLOAT,
    MAGNITUDE_TYPE VARCHAR,
    PLACE VARCHAR,
    LONGITUDE FLOAT,
    LATITUDE FLOAT,
    DEPTH_KM FLOAT,
    REJECT_REASON VARCHAR,
    PROJECTED_AT TIMESTAMP_TZ NOT NULL
)
COMMENT = 'One typed projection per RAW source observation, including rejects';
