-- Phase 0 Snowflake setup. Review before running with an account admin role.
-- This file creates empty project objects. It does not load data or run compute.
-- IF NOT EXISTS does not update an existing object's settings; verify after execution.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS QUAKEWATCH_ROLE;
CREATE DATABASE IF NOT EXISTS QUAKEWATCH;
CREATE SCHEMA IF NOT EXISTS QUAKEWATCH.RAW;
CREATE SCHEMA IF NOT EXISTS QUAKEWATCH.CURATED;

CREATE WAREHOUSE IF NOT EXISTS QUAKEWATCH_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE STAGE IF NOT EXISTS QUAKEWATCH.RAW.USGS_JSON_STAGE
  FILE_FORMAT = (TYPE = JSON);

GRANT USAGE ON DATABASE QUAKEWATCH TO ROLE QUAKEWATCH_ROLE;
GRANT USAGE ON SCHEMA QUAKEWATCH.RAW TO ROLE QUAKEWATCH_ROLE;
GRANT USAGE ON SCHEMA QUAKEWATCH.CURATED TO ROLE QUAKEWATCH_ROLE;
GRANT USAGE ON WAREHOUSE QUAKEWATCH_WH TO ROLE QUAKEWATCH_ROLE;

-- Internal-stage WRITE requires READ as well.
GRANT READ ON STAGE QUAKEWATCH.RAW.USGS_JSON_STAGE TO ROLE QUAKEWATCH_ROLE;
GRANT WRITE ON STAGE QUAKEWATCH.RAW.USGS_JSON_STAGE TO ROLE QUAKEWATCH_ROLE;

GRANT CREATE TABLE ON SCHEMA QUAKEWATCH.RAW TO ROLE QUAKEWATCH_ROLE;
GRANT CREATE TABLE ON SCHEMA QUAKEWATCH.CURATED TO ROLE QUAKEWATCH_ROLE;
GRANT CREATE VIEW ON SCHEMA QUAKEWATCH.CURATED TO ROLE QUAKEWATCH_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA QUAKEWATCH.CURATED TO ROLE QUAKEWATCH_ROLE;

-- Personal project account: grant this role to the known account user.
GRANT ROLE QUAKEWATCH_ROLE TO USER KARTHIK12MOHAN;
