-- Phase 2 revision history and current-event view. Local definition only.
-- Apply with QUAKEWATCH_ROLE after cost approval and table-shape inspection.
-- Grain: one (CANONICAL_EVENT_ID, SOURCE_UPDATED_AT, PAYLOAD_HASH).
-- The Snowpark procedure must deduplicate and MERGE by that full key;
-- Snowflake standard-table constraints alone do not enforce uniqueness.
CREATE TABLE IF NOT EXISTS QUAKEWATCH.CURATED.FACT_EVENT_REVISION (
    CANONICAL_EVENT_ID VARCHAR NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    PAYLOAD_HASH VARCHAR(64) NOT NULL,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    ASSOCIATED_IDS VARIANT,
    ORIGIN_TIME TIMESTAMP_TZ NOT NULL,
    FETCHED_AT TIMESTAMP_TZ NOT NULL,
    CURATED_AT TIMESTAMP_TZ NOT NULL,
    SOURCE_STATUS VARCHAR NOT NULL,
    MAGNITUDE FLOAT,
    MAGNITUDE_TYPE VARCHAR,
    PLACE VARCHAR,
    LONGITUDE FLOAT,
    LATITUDE FLOAT,
    DEPTH_KM FLOAT,
    STAGING_PARSER_VERSION VARCHAR NOT NULL,
    STAGE_FILE_NAME VARCHAR NOT NULL,
    STAGE_FILE_ROW_NUMBER NUMBER(38, 0) NOT NULL
)
COMMENT = 'One distinct canonical USGS event revision, including tombstones';

-- Rank all revisions first. Filtering deleted rows before ranking would
-- incorrectly resurrect an older active revision after a tombstone.
CREATE OR REPLACE VIEW QUAKEWATCH.CURATED.EVENT_CURRENT AS
WITH RANKED_REVISIONS AS (
    SELECT
        FACT_EVENT_REVISION.*,
        ROW_NUMBER() OVER (
            PARTITION BY CANONICAL_EVENT_ID
            ORDER BY SOURCE_UPDATED_AT DESC, FETCHED_AT DESC, PAYLOAD_HASH DESC,
                     STAGE_FILE_NAME DESC, STAGE_FILE_ROW_NUMBER DESC
        ) AS REVISION_RANK
    FROM QUAKEWATCH.CURATED.FACT_EVENT_REVISION
)
SELECT
    CANONICAL_EVENT_ID,
    SOURCE_EVENT_ID,
    ASSOCIATED_IDS,
    ORIGIN_TIME,
    SOURCE_UPDATED_AT,
    FETCHED_AT,
    CURATED_AT,
    SOURCE_STATUS,
    MAGNITUDE,
    MAGNITUDE_TYPE,
    PLACE,
    LONGITUDE,
    LATITUDE,
    DEPTH_KM,
    PAYLOAD_HASH,
    STAGING_PARSER_VERSION
FROM RANKED_REVISIONS
WHERE REVISION_RANK = 1 AND SOURCE_STATUS <> 'deleted';
